### ISSUE TITLE
Adding download button on android apps (VI: thêm nút tải xuống cho app android)

### ISSUE THREAD

**Issue by Karutovn** [anime-vsub/desktop-web#147]
Em muốn thêm nút download để tải phim về khi sử dụng app (nếu tải về được cành tốt) (cơ bản là em cần xem phim khi không có mạng)
I want to adding download button because i need to watchong anime when i have no internet

**Comment by tachibana-shin** [comment]
This was planned by the original author of the application. The entire source code is even available but I don't have time to port them to android you can see this branch: https://github.com/anime-vsub/desktop-web/tree/feat-offline
