### ISSUE TITLE
use `onSnapshot` strategy in `history` at `header`

### ISSUE THREAD

**Issue by tachibana-shin** [anime-vsub/desktop-web#15]

**Comment by tachib-shin** [comment]
なぜ、このような問題が起こるのでしょうか？

**Comment by tachib-shin** [comment]
this proposal has been reverted to https://github.com/anime-vsub/desktop-web/commit/ed1c19eda3ca7368eb8226f04cd6d73450ec66a7 due to client bandwidth utilization problems but APIs are retained
