### ISSUE TITLE
Play load error: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by hotboykila2014** [anime-vsub/desktop-web#152]
Chắc bạn đọc được tiếng Việt nhỉ ?
Mình bị lỗi như tiêu đề và không thể xem được bất kỳ phim nào trên website.

**Comment by tachibana-shin** [comment]
https://github.com/anime-vsub/desktop-web/commit/14a8e96cc9f1bef1e871ad7838dac0cfe4a5af9d
