### ISSUE TITLE
Chức năng tải xuống khá bất tiện và hay lỗi.

### ISSUE THREAD

**Issue by hotboykila2014** [anime-vsub/desktop-web#155]
Web một lần chỉ có thể tải 1 video/tab, nếu mở thêm tab để tải cùng lúc nhiều video thì sẽ tải chậm hoặc báo lỗi không tải được.
Đây là 2 thông báo lỗi mình thường gặp khi tải:

`Error: NotReadableError: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.`

```
Video download failed
Error: [object Response]
```
Mình góp ý là nên thêm tính năng để có thể chọn tải cùng lúc nhiều video.
Nếu không được thì mong bạn fix để mình có thể mở nhiều tab tải cùng lúc cũng được.
Cảm ơn bạn.

**Comment by hotboykila2014** [comment]
Nhân tiện thì mình có tải file apk về cài trên giả lập để xem xem tải video trên app có ok hơn không thì thấy app không có nút tải xuống.
Kế bên nút "chia sẻ" là nút "lưu", không có nút "tải".

**Comment by tachibana-shin** [comment]
We do not intend to add this functionality because the server has limited the requests that can be made
