### ISSUE TITLE
[feature]: add mote Movies like youtube

### ISSUE THREAD

**Issue by XuanDong2410** [anime-vsub/desktop-web#24]

**Comment by tachib-shin** [comment]
What is this? I don't think we need a function like this. @tachibana-shin

**Comment by tachibana-shin** [comment]
> What is this? I don't think we need a function like this. @tachibana-shin

It seems that some users like this mode. I have implemented the necessary APIs. Please complete it.

![360102](https://user-images.githubusercontent.com/45375496/203011912-b5189b65-5ee3-4653-b6c4-47cd726f9206.jpg)
